In [1]:
import pandas as pd
import json
import os
from pprint import pprint

In [2]:
video_categ_file=os.path.join('Resources','Raw Data','category_id.json')

print(video_categ_file)

Resources\Raw Data\category_id.json

In [3]:
category_raw_df = pd.read_json(video_categ_file)

df = pd.DataFrame([i for i in category_raw_df['items']])

df.head()

,kind,etag,id,snippet
0,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...",1,"{'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit..."
1,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UZ1oLIIz2dxIhO45Z...",2,"{'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit..."
2,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10,"{'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit..."
3,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...",15,"{'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit..."
4,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/9GQMSRjrZdHeb1OEM...",17,"{'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit..."

In [4]:
video_categ_raw_df = pd.DataFrame(columns = ['Category_id','Category_Name'])
video_categ_raw_df['Category_id'] = df['id']
video_categ_raw_df['Category_Name'] = df['snippet']
video_categ_raw_df.head()

  Category_id                                      Category_Name
0           1  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
1           2  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
2          10  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
3          15  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...
4          17  {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ', 'tit...

In [5]:
video_categ_df = pd.concat([video_categ_raw_df.drop('Category_Name', axis=1), pd.DataFrame(video_categ_raw_df['Category_Name'].tolist())], axis=1)
#video_categ_df

video_category1_df = video_categ_df.drop(['channelId', 'assignable'], axis = 1)
#video_category1_df

video_category_df = video_category1_df.rename(columns={'title':'Category_Name'})
video_category_df

   Category_id          Category_Name
0            1       Film & Animation
1            2       Autos & Vehicles
2           10                  Music
3           15         Pets & Animals
4           17                 Sports
5           18           Short Movies
6           19        Travel & Events
7           20                 Gaming
8           21          Videoblogging
9           22         People & Blogs
10          23                 Comedy
11          24          Entertainment
12          25        News & Politics
13          26          Howto & Style
14          27              Education
15          28   Science & Technology
16          29  Nonprofits & Activism
17          30                 Movies
18          31        Anime/Animation
19          32       Action/Adventure
20          33               Classics
21          34                 Comedy
22          35            Documentary
23          36                  Drama
24          37                 Family
25          38                Foreign
26          39                 Horror
27          40         Sci-Fi/Fantasy
28          41               Thriller
29          42                 Shorts
30          43                  Shows
31          44               Trailers

In [ ]:
video_category_df

In [6]:
import pandas as pd

import pymongo
import csv
import json
from pymongo import MongoClient
client = MongoClient()
client = MongoClient('localhost', 27017)
db=client['youtube_db']

In [ ]:
category = db.video_category.find()
ch_info = db.top_channel_info.find()
for i in ch_info:
    print(i)

In [ ]:
cnt = 0
for ch in db.top_channel_info.find():
    ch_id = ch['Channel_id']
    ch_cat_name = ch['Category_name']
    cat_id = db.video_category.find_one({ "Category_Name": str(ch_cat_name) })['Category_id']
    db.top_channel_info.update_one({"Channel_id": ch_id}, {'$set': {"Category_id": cat_id}})
    cnt +=1
    print(cnt)

In [ ]:
cnt = 0
for chann in db.general_channel_info.find():
    ch_id = chann['channelid']
    ch_cat_id = chann['videocategoryid']
    cat_name = db.video_category.find_one({ "Category_id": str(ch_cat_id) })['Category_Name']
    db.general_channel_info.update_one({"channelid": ch_id}, {'$set': {"Category_Name": cat_name}})
    cnt +=1
    print(cnt)
print(cnt)

In [ ]:
#general_channel_info & general_channel_details_info

general_channel_merged = db.general_channel_details_info.aggregate([
   {
     '$lookup':
       {
         'from': "general_channel_info",
         'localField': "Channel_id",
         'foreignField': "channelid",
         'as': "details1"
       }
  },
  { '$unwind': "$details1" },
  {
    '$project': {
        "Channel_id": 1,
        "Channel_title": 1,
        "Created_date": 1,
        "Video_count": 1,
        "Views_count":1,
        "Subscription_count": 1,
        "Subscription_count_hidden": 1,
        "Country": 1,
        "Category_id": "$details1.videocategoryid",
        "Category_name": "$details1.Category_Name"
    }
       
  }
 
])

In [ ]:
#merged_top_channel merged_general_channel
general_top_merged = db.merged_top_channel.aggregate( [
   { '$unionWith': "merged_general_channel" }
] )

In [ ]:
merged_general_top_channel=db['merged_general_top_channel']
merged_general_top_channel.drop()
for row1 in general_top_merged:
    db.merged_general_top_channel.insert_one(row1)

In [ ]:
for r in general_top_merged:
    print(r)

In [ ]:
video_category_df.head()

In [8]:
from config import cloudM ,cloudMpassword 
#print (cloudM,cloudMpassword)
cloudstr=f'mongodb+srv://{cloudM}:{cloudMpassword}@supriyada.h7evx.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
#mongodb+srv://{cloudM}:{cloudMpassword}@supriyada.h7evx.mongodb.net/myFirstDatabase?retryWrites=true&w=majority    
#mongodb+srv://{cloudM}:{cloudMpassword}@supriyada.h7evx.mongodb.net/test
###
#using the example string above create your own connection string . 
#this is what you saved in the notepad during the cluster creation process

##
cloudclient = MongoClient(cloudstr)
#print(cloudstr)

db=cloudclient['youtube_cloud_db']
colmanager=db['youtube_collection']
colmanager.insert_many(video_category_df.to_dict('records'))
colmanager.find()

In [ ]:
db.top_channel_info.update_one({"Channel_id": "UCq-Fj5jknLsUf-MWSy4_brA"}, {'$set': {"Category_id": "10"}})

db.top_channel_info.update_one({"Channel_id": ch_id}, {'$set': {"Category_id": cat_id}})

In [ ]:
#UCq-Fj5jknLsUf-MWSy4_brA -- test id
for ch in category:
    id = 2
    id2 = db.ch.find()  #ch['Category_id']
    if (id == int(id2)):
        print(ch['Category_Name'])